//This file was automatically generated by the genval generator v1.4
//Please don't modify it manually. Edit your entity tags and then
//run go generate

package empty

type validatable interface {
	Validate() error
}

func validate(i interface{}) error {
	if v, ok := i.(validatable); ok {
		return v.Validate()
	}
	return nil
}
